version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "America/Sao_Paulo"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "marciodojr"
    rebase-strategy: auto
    target-branch: "master"
    versioning-strategy: lockfile-only
    commit-message:
      trailers:
        - changelog: "dependency"
    allow:
      - dependency-name: "incluirtecnologia*"
        update-types: ["version-update:semver-minor"]
      - dependency-type: "all"
        update-types: ["version-update:semver-patch"]
    auto-merge:
        ignore:
            - dependency-name: "incluirtecnologia*"
